spring:
  application:
    name: iTransition-course-project
  servlet:
    multipart:
      max-request-size: 15MB
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ec2-52-72-56-59.compute-1.amazonaws.com:5432/df931dkt6mh7gb
    username: kbidcuasuipddx
    password: ddaa5eebac6855fc200ff9716775ed839d8229d487cf947f99365a52853e6407
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  sql:
    init:
      mode: always

server:
  port: 8080
cloudinary:
  cloud-name: itransition-course-project
  api-key: 581912988294536
  api-secret: _0Rr-DFn4ABGCseE5MPfc4LgwsA